# Application Name
spring.application.name=CampFinder

# DataSource Configuration
# Configure these in application-local.properties
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=

# Hibernate Configuration
spring.jpa.properties.hibernate.ddl-auto=validate
spring.jpa.properties.jadira.usertype.autoRegisterUserTypes=true
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP
spring.jpa.open-in-view=false

# Recreation API Configuration
# Configure this in application-local.properties
# recreation.baseUrl=

# Pushover Configuration
# Configure these in application-local.properties
# pushover.api_token=
# pushover.user_token=